networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/aspnet_local.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=postgres;Password=LodgingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - "8000:80"
  data:
    environment:
      POSTGRES_PASSWORD: LodgingData@2020
    image: postgres:12
    networks:
      - locally
  DBAdmin:
    environment:
      POSTGRES_PASSWORD: LodgingData@2020
      image: dpage/pgadmin4
      depends_on:
        - data
      networks:
        - locally
      ports:
        - 8089:80
  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9411:9411

version: '3.8'
